# Generated by Django 5.0.6 on 2024-11-06 02:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'db_table': 'mark',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dpi', models.CharField(max_length=13, unique=True, verbose_name='DPI')),
                ('first_name', models.CharField(max_length=75, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=75, verbose_name='Apellidos')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('gender', models.CharField(choices=[('F', 'FEMENINO'), ('M', 'MASCULINO')], max_length=1, verbose_name='Género')),
                ('phone', models.CharField(max_length=8, verbose_name='Celular')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietarios',
                'db_table': 'owner',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectores',
                'db_table': 'section',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Nombre')),
                ('description', models.CharField(max_length=60, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'status',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, unique=True, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo',
                'verbose_name_plural': 'Tipos',
                'db_table': 'type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Aldea',
                'verbose_name_plural': 'Aldeas',
                'db_table': 'village',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=15, verbose_name='Número')),
                ('serie', models.CharField(max_length=45, verbose_name='Serie')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charge.mark', verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Contador',
                'verbose_name_plural': 'Contadores',
                'db_table': 'meter',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charge.meter', verbose_name='Contador')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charge.owner', verbose_name='Propietario')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charge.section', verbose_name='Sector')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'service',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('reading', models.CharField(max_length=5, verbose_name='Lectura')),
                ('diference', models.CharField(max_length=5, verbose_name='Diferencia')),
                ('excess', models.CharField(max_length=3, verbose_name='Exceso')),
                ('total', models.FloatField(verbose_name='Total a pagar')),
                ('debt', models.FloatField(verbose_name='Mora')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charge.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de servicio',
                'verbose_name_plural': 'Detalles de servicios',
                'db_table': 'service_detail',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='owner',
            name='status',
            field=models.ForeignKey(default=22, on_delete=django.db.models.deletion.PROTECT, to='charge.status', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='status',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charge.type', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='section',
            name='village',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='charge.village', verbose_name='Aldea'),
        ),
    ]
